FROM python:3.8-slim

COPY . /app/

RUN \
  apt-get update -qq && \
  apt-get install -qq gcc postgresql python3-psycopg2 libpq-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN python /app/setup.py install
RUN pip install -r /app/requirements-dev.txt

WORKDIR /app

ENTRYPOINT ["/bin/sh"]
