version: "3"

services:
  postgres:
    image: postgres:13.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - .:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  scraper:
    build: .
    env_file:
      - .env
    command: run_scraping.sh
    volumes:
      - .:/app
    depends_on:
      - "postgres"

volumes:
  database_data:
    driver: local
