components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /ur_parts/:
    get:
      description: 'Load data of UrParts with parameters:


        - **limit**: Data limit. To specify no limit, set -1.

        - **vehicle_brand**: Vehicle brand. e.g. ''Ammann''

        - **vehicle_category**: Vehicle category/type. e.g. ''Roller Parts''

        - **vehicle_model**: Vehicle model name. e.g. ''ASC100''

        - **part_name**: Part model name. e.g. ''ND021197''

        - **part_category**: Part category/type. e.g. ''bolt'''
      operationId: fetch_data_ur_parts__get
      parameters:
      - in: query
        name: limit
        required: false
        schema:
          default: 10
          title: Limit
          type: integer
      - in: query
        name: vehicle_brand
        required: false
        schema:
          title: Vehicle Brand
          type: string
      - in: query
        name: vehicle_category
        required: false
        schema:
          title: Vehicle Category
          type: string
      - in: query
        name: vehicle_model
        required: false
        schema:
          title: Vehicle Model
          type: string
      - in: query
        name: part_name
        required: false
        schema:
          title: Part Name
          type: string
      - in: query
        name: part_category
        required: false
        schema:
          title: Part Category
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Fetch Data
